# Mixcloud custom convert
mixcloud mp3 * *
        # RB:{BITRATE=-B %B}T:{START=-ss %s}
        [ffmpeg] -loglevel quiet -i $URL$ $START$ -f wav - | [lame] --silent -q $QUALITY$ $BITRATE$ - -

mixcloud pcm * *
        # RB:{BITRATE=-B %B}T:{START=-ss %s}
        [ffmpeg] -loglevel quiet -i $URL$ $START$ -f s16le -

mixcloud flc * *
        # RB:{BITRATE=-B %B}T:{START=-ss %s}
        [ffmpeg] -loglevel quiet -i $URL$ $START$ -f flac -
